name: OST tr-suite-master trigger
 
on:
  issue_comment:
    types: [created]
 
jobs:
  trigger-ost:
    if: |
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/ost') &&
      (
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    uses: oVirt/ovirt-system-tests/.github/workflows/ost.yaml@master
    with:
      pr_url: https://github.com/oVirt/terraform-provider-ovirt/pull/317
      suite: tr-suite-master
      distro: rhel8
