version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gosec
    - importas
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        source: ^package main
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
