name: OCP Installer compilation with terraform provider patch
on:
  push:
    branches: [ v0 ]
  pull_request:
    branches: [ v0 ]
  workflow_dispatch:
jobs:
  compile-and-build-rpm:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
    steps:
      - uses: actions/checkout@v2
      - name: prepare env
        run: |
           mkdir -p ${GITHUB_WORKSPACE}/BUILDROOT  ${GITHUB_WORKSPACE}/SOURCES
           yum install -y git createrepo_c rpm-build golang
      - name: clone OCP installer and compile it with terraform provider patch 
        run: | 
          echo "WORKSPACE is ${GITHUB_WORKSPACE}"
          cd ../../
          echo cloning installer
          git clone https://github.com/openshift/installer
          INSTALLER_PATH=$(pwd)/installer
          echo cloning installer completed
          rm -rf ${INSTALLER_PATH}/vendor/github.com/ovirt/terraform-provider-ovirt/
          mkdir ${INSTALLER_PATH}/vendor/github.com/ovirt/terraform-provider-ovirt
          echo start copy of terraform provider dir to installer
          cp -r ${GITHUB_WORKSPACE}/* ${INSTALLER_PATH}/vendor/github.com/ovirt/terraform-provider-ovirt/
          echo copy of terraform provider dir to installer completed
          echo compiling OCP installer
          cd installer
          ./hack/build.sh
          echo compiling OCP installer completed
      - name : Build RPM
        run: |
          echo generating package suffix
          cd ${GITHUB_WORKSPACE}
          cd ../../
          INSTALLER_PATH=$(pwd)/installer
          cd ${INSTALLER_PATH}/vendor/github.com/ovirt/terraform-provider-ovirt/
          SUFFIX=.$(date -u +%Y%m%d%H%M%S).git$(git rev-parse --short HEAD)
          echo "SUFFIX=${SUFFIX}"
          echo prepering files for rpmbuild
          mkdir -p ${GITHUB_WORKSPACE}/ocp-installer-bin
          cd ${GITHUB_WORKSPACE}
          cp ${INSTALLER_PATH}/bin/openshift-install ${GITHUB_WORKSPACE}/ocp-installer-bin/
          cp ${INSTALLER_PATH}/bin/openshift-install ${GITHUB_WORKSPACE}/SOURCES/
          tar cvzf  tr-ocp-installer.tar.gz ${GITHUB_WORKSPACE}/ocp-installer-bin/
          cp tr-ocp-installer.tar.gz ${GITHUB_WORKSPACE}/SOURCES
          rpmbuild -D "_topdir ${GITHUB_WORKSPACE}" -D "release_suffix ${SUFFIX}" -ba tr-ocp-installer.spec
      - name: Collect artifacts
        run: |
          echo collecting artifacts
          cd ${GITHUB_WORKSPACE}
          mkdir -p ${GITHUB_WORKSPACE}/exported-artifacts
          find . -iname \*rpm -exec mv "{}" exported-artifacts/ \;
          ls -l ${GITHUB_WORKSPACE}/exported-artifacts
      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts
