name: OST tr-suite-master trigger
 
on:
  issue_comment:
    types: [created]
 
jobs:
  trigger-ost:
    uses: oVirt/ovirt-system-tests/.github/workflows/ost.yaml@master
    with:
      comment: " tr-suite-master rhel8"
